### ISSUE TITLE
Lita always looks offline

### ISSUE THREAD

**Issue by amaltson** [jimmycuadra/lita-hipchat#23] opened 2015-01-21 03:13 UTC
I'm finding since we upgraded to HipChat Server v1.1.5, the Lita bot no longer appears to be online. Strangely though, it still joins rooms and answers queries, just appearing to be offline.

Lita 4.1.0
lita-hipchat 2.1.1
HipChat Server 1.1.5

**Comment by jimmycuadra** [comment] 2015-01-21 05:06
This is a confirmed bug with the HipChat client. Hopefully it will be resolved soon!

Dupe of #21.

**Closed by jimmycuadra** 2015-01-21 05:06 UTC
Labels: duplicate

**Comment by alhafoudh** [comment] 2015-02-13 20:59
I think its not bug in HipChat client. The presence implementation in hubot is slightly different: https://github.com/hipchat/hubot-hipchat/blob/master/src/connector.coffee

**Comment by esigler** [comment] 2015-02-16 21:15
FYI, internally this is being tracked as an issue with the Hipchat Mac OSX client, HC-7228.

**Comment by WarhammerMarine** [comment] 2015-03-07 00:54
Also I just installed the latest lita and lita-hipchat and the bot is active but in Hipchat it shows as offline. I am not using Hipchat Server.

**Comment by amaltson** [comment] 2015-07-09 14:46
I can confirm this is totally fixed now.
